language: node_js
dist: trusty
sudo: required

node_js:
  - "6.1"

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable
