language: node_js
dist: trusty
sudo: required

node_js:
  - "6.1"
  
git:
  depth: 1

cache:
  directories:
    - node_modules

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


after_success:
  - npm run build
  - ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable
