sudo: false
language: node_js

node_js:
  - "6.1"

git:
  depth: 1

before_install:
  - npm install codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run build
  -  test $TRAVIS_PULL_REQUEST_BRANCH = "" && ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN

branches:
  only:
    - master
